Avya/Models/CollectionViewModel.cs
using System.ComponentModel.DataAnnotations;
using Library.Enum;

namespace Avya.Models
{
    public class CollectionViewModel : BaseEntityModel
    {
        public bool? Favourite { get; set; }

        [Required(ErrorMessage = "Please select a collection type")]
        [Display(Name = "Type")]
        public MediaTypeCode? CollectionType { get; set; }

        [Display(Name = "No. of Items")]
        public int ItemCount { get; set; }

        public string UserId { get; set; }
    }
}

Avya/Controllers/CollectionController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Avya.Models;
using Data.DbContext;
using Data.DTO;
using Data.Entity;
using Library.Mapper;

namespace Avya.Controllers
{
    [Authorize]
    public class CollectionController : BaseController
    {
        public CollectionController(AvyaDbContext _db) : base(_db)
        {
        }

        // GET: Collection
        public ActionResult Index()
        {
            var results = db.GetAllUserCollections(UserId)
                        .Select(x => Mapper.Map<CollectionDTO, CollectionViewModel>(x))
                        .ToList();

            return View(results);
        }
        public ActionResult Create()
        {
            return View();
        }

        // POST: Collection/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CollectionType,UserId,Name")] CollectionViewModel collectionViewModel)
        {
            if (ModelState.IsValid)
            {
                var entity = Mapper.Map<CollectionViewModel, Collection>(collectionViewModel);
                db.Collections.Add(entity);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(collectionViewModel);
        }

        // POST: Collection/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CollectionType,UserId,Name,Favourite")] CollectionViewModel collectionViewModel)
        {
            if (ModelState.IsValid)
            {
                var c = Mapper.Map<CollectionViewModel, Collection>(collectionViewModel);
                db.Entry(c).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(collectionViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Delete(int id)
        {
            bool isSuccess = true;
            if (ModelState.IsValid)
            {
                db.Entry(new Collection { Id = id }).State = EntityState.Deleted;
                db.SaveChanges();
            }
            return Json(isSuccess);
        }
    }
}

Avya/Views/Collection/Create.cshtml
@using Microsoft.AspNet.Identity;
@using Library.Enum;
@model Avya.Models.CollectionViewModel

@{
    ViewBag.Title = "Add New Collection";
}
@{
    var types = Enum.GetValues(typeof(MediaTypeCode));
}
<center><h2>Add new collection</h2></center>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="ui-corner-all ui-widget-content collection-details">
        <div class="form-horizontal create-form">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <center>
                    <div class="col-md-12">
                        @foreach (var type in types)
                    {
                    <div style="display:inline-block;">
                        @Html.RadioButtonFor(m => m.CollectionType, (int)type, new { @id = type + "-radBtn", @class = "typeRadBtns" })
                        <label for="@type-radBtn"></label>
                    </div>
                    }
                        <div>
                            @Html.ValidationMessageFor(m => m.CollectionType, "", new { @class = "text-danger" })
                        </div>
                    </div>

                </center>
            </div>
            <div class="form-group">
                <center>
                    <div class="col-md-offset-4 col-md-3 addNameField">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Name", @required = "required" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                    @Html.HiddenFor(m => m.UserId, new { Value = User.Identity.GetUserId() })
                    <div class="col-md-1 btnContainer">
                        <input type="submit" value="" class="save-btn btn" />
                    </div>
                    <div class="col-md-1 btnContainer">
                        <input type="button" value="" class="cancel-btn btn" onclick="location.href='@Url.Action("Index", "Collection")';return false;" />
                    </div>
                </center>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Avya/Views/Collection/Index.cshtml
@using Microsoft.AspNet.Identity
@using Library.Enum
@using Avya.Helpers
@using Avya.Models
@using Avya.Extensions
@model IEnumerable<CollectionViewModel>

@{
    ViewBag.Title = "My Collections";
    var vdd = new ViewDataDictionary
    {
        { "entity", Model.GetEntityName() }
    };

    var sort = string.Empty;
    var order = string.Empty;

    if (QueryStringHelper.ValidQueryStrings(Request, "sort", "order") && User.Identity.IsAuthenticated)
    {
        sort = Request["sort"].ToString();
        order = Request["order"].ToString();

        if (!QueryStringHelper.IsValidSortAndOrder(sort, order))
        {
            sort = "name";
            order = "asc";
        }
    }
}

<script type="text/javascript">
    $(function () {
        // Use cookie to remember last open tab
        // http://stackoverflow.com/a/14467706

        var index = 'homePageTabs';
        var dataStore = window.sessionStorage;
        try {
            var oldIndex = dataStore.getItem(index);
        } catch (e) {
            var oldIndex = 0;
        }
        $('#tabs').tabs({
            active: oldIndex,
            activate: function (event, ui) {
                var newIndex = ui.newTab.parent().children().index(ui.newTab);
                dataStore.setItem(index, newIndex)
            }
        });
    });
</script>
@Html.Partial("_EditEntityPartial", vdd)
@Html.Partial("_DeleteDialogPartial", vdd)
<center><h2>@User.Identity.GetUserName()'s Collections</h2></center>
<div id="tabs" class="centered">
    @{
        var types = Enum.GetValues(typeof(MediaTypeCode));
    }
    <div class="newBtn-container">
        @Html.ActionLink(" ", "Create", null, new { @class = "new-btn" })
    </div>
    <ul>
        @foreach (var type in types)
        {
            <li><a href="#@type"><span></span></a></li>
        }
    </ul>
    @foreach (var type in types)
    {
        <div id="@type">
            <hr />
            <div class="row">
                <div class="row">
                    <div class="col-md-1 col-md-offset-3">
                        <div class="header fav-header">
                            <a href="@Url.Action("Index", "Collection", new { sort = "fav", order = (order == "asc") ? "desc" : "asc" })">
                                <span class="@(@sort == "fav" || @sort == "" ? (@order == "asc" ? "fav-off" : "fav-on") : "")"></span>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="header">
                            <a href="@Url.Action("Index", "Collection", new { sort = "name", order = (order == "asc") ? "desc" : "asc" })">
                                @Html.DisplayNameFor(model => model.Name) <i class="fa @(@sort == "name" ? (@order == "asc" ? "fa-arrow-up" : "fa-arrow-down") : "")" aria-hidden="true"></i>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="header">
                            <a href="@Url.Action("Index", "Collection", new { sort = "items", order = (order == "asc") ? "desc" : "asc" })">
                                @Html.DisplayNameFor(model => model.ItemCount)
                                <i class="fa @(@sort == "items" ? (@order == "asc" ? "fa-arrow-up" : "fa-arrow-down") : "")" aria-hidden="true"></i>
                            </a>
                        </div>
                    </div>
                </div>
                @foreach (var item in Model.Where(x => x.CollectionType == (MediaTypeCode)type).SortAndOrderBy(sort, order))
                {
                    <div class="itemRow col-md-12">
                        <div class="anchor-container">
                            @{ var fav = (bool)item.Favourite; }
                            <div class="col-md-1 col-md-offset-3">@Html.CheckBoxFor(modelItem => fav, new { @class = "fav-cb", onclick = "editField(this,{id: " + item.Id + ", name: '" + item.Name + "', type:" + (int)item.CollectionType + "})" }) </div>
                            <a class="row-anchor" href="@Url.RouteUrl(item.ItemCount > 0 ? "DetailIndex" : "CreateDetailView", new { cid = item.Id, t = (int)item.CollectionType, c = item.Name })">
                                <div class="col-md-3 toEdit collection-name">@Html.DisplayFor(modelItem => item.Name)</div>
                                <div class="col-md-3 editor">
                                    <input type="text" value="@item.Name" size="@item.Name.Length" name="name" class="form-control" />
                                </div>
                                <div class="col-md-1 num-items">@Html.DisplayFor(modelItem => item.ItemCount)</div>
                            </a>
                        </div>
                        <div class="col-md-2">
                            @Html.ActionLink(" ", null, null, new { @class = "edit-btn", onclick = "editField(this,{id: " + item.Id + ", name: '" + item.Name + "', type:" + (int)item.CollectionType + "})" })
                            @Html.ActionLink(" ", null, null, new { @class = "bin-btn", onclick = "showDeleteDialog({ id: " + item.Id + ", name: '" + item.Name + "', entity: 'c'})" })
                        </div>
                    </div>
                                }
            </div>
            <hr />
        </div>
                                }
    @using (Html.BeginForm("Edit", Model.GetEntityName(), FormMethod.Post, new { id = "edit-form" }))
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("Id")
        @Html.Hidden("Name")
        @Html.Hidden("CollectionType")
        @Html.Hidden("UserId", User.Identity.GetUserId())
        @Html.Hidden("Favourite")
    }
</div>